### ISSUE TITLE
多人游戏，玩家站在蒸汽锅炉上被踢导致无法加入游戏

### ISSUE THREAD

**Issue by YELANDAOKONG** [moguang2004/Create-New-Horizon#58]
Caused by: java.lang.AssertionError: Damage type not found in registry. This is a bug from that mod that added it!: DamageType[msgId=gtceu.heat, scaling=WHEN_CAUSED_BY_LIVING_NON_PLAYER, exhaustion=0.0, effects=HURT, deathMessageType=DEFAULT]

[16:29:47] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:44459
net.minecraft.ReportedException: Colliding entity with block
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.AssertionError: Damage type not found in registry. This is a bug from that mod that added it!: DamageType[msgId=gtceu.heat, scaling=WHEN_CAUSED_BY_LIVING_NON_PLAYER, exhaustion=0.0, effects=HURT, deathMessageType=DEFAULT]
	at net.mehvahdjukaar.dummmmmmy.network.ClientBoundDamageNumberMessage.encodeDamage(ClientBoundDamageNumberMessage.java:50) ~[dummmmmmy-1.20-2.0.2.jar%23484!/:?]
	at net.mehvahdjukaar.dummmmmmy.network.ClientBoundDamageNumberMessage.<init>(ClientBoundDamageNumberMessage.java:41) ~[dummmmmmy-1.20-2.0.2.jar%23484!/:?]
	at net.mehvahdjukaar.dummmmmmy.common.ModEvents.onEntityDamage(ModEvents.java:73) ~[dummmmmmy-1.20-2.0.2.jar%23484!/:?]
	at net.minecraft.world.entity.player.Player.wrapOperation$dgc000$dummmmmmy$actuallyHurt_setHealth(Player.java:7734) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.player.Player.m_6475_(Player.java:921) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.player.Player.m_6469_(Player.java:840) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:695) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at com.gregtechceu.gtceu.utils.EntityDamageUtil.applyHeatDamage(EntityDamageUtil.java:56) ~[gtceu-1.20.1-1.4.4.jar%23531!/:1.4.4]
	at com.gregtechceu.gtceu.utils.EntityDamageUtil.applyTemperatureDamage(EntityDamageUtil.java:32) ~[gtceu-1.20.1-1.4.4.jar%23531!/:1.4.4]
	at com.gregtechceu.gtceu.common.block.FluidPipeBlock.m_7892_(FluidPipeBlock.java:164) ~[gtceu-1.20.1-1.4.4.jar%23531!/:1.4.4]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60682_(BlockBehaviour.java:766) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.Entity.m_20101_(Entity.java:998) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.Entity.m_146872_(Entity.java:773) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2195) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2132) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.player.Player.m_7023_(Player.java:1423) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2605) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:501) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23642!/:?]
	... 9 more

**Comment by YELANDAOKONG** [comment]
主机重启游戏已解决
